version: '3.8'

services:

    # NestJS
    nestdev:
        container_name: studies-nestjs
        image: nestjs-api-dev:1.0.0
        env_file:
            - .env
        build:
            context: .
            target: local
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - ${APP_PORT}:${APP_PORT}
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - nestpostgres
        links:
            - nestpostgres

    # DB - Postgres
    nestpostgres:
        container_name: studies-postgres
        image: postgres:14.1-alpine
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${DB_POSTGRES_USER}
            - POSTGRES_PASSWORD=${DB_POSTGRES_PASS}
        ports:
            - 5432:5432
        restart: always
        volumes: 
            - nest-postgres-volume:/var/lib/postgresql/data
            - ./docker/postgres:/docker-entrypoint-initdb.d
        networks:
            - nesjs-network

volumes:
    nest-postgres-volume:

networks:
    nesjs-network: